apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-data01-clone 
spec:
  storageClassName: longhorn-demo
  dataSource:
    name: pvc-mysql-data01 
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

