apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-data01
  namespace: student1
  labels:
    name: mysql-data01
    type: longhorn
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '20'
    volumeHandle: mysql-data01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-data01
  namespace: student1
  labels:
    type: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeName: pv-mysql-data01
  storageClassName: longhorn
